name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: ./Python
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry install -E all
    - name: Run test suite
      working-directory: ./Python
      run: |
        poetry run pytest
    - name: Upload coverage result
      working-directory: ./Python
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
         if [ -n "${COVERALLS_REPO_TOKEN}" ]; then
            poetry run coveralls
         fi
      if: ${{ matrix.os == 'ubuntu-latest' && contains(matrix.python-version, '3.10') }}
